theme = "smol"
baseURL = "https://aesthetic-dodol-7dd559.netlify.app/"
languageCode = "en-us"
title = "Esports Rankings"

# Parameters
[params]
    subtitle = "Using Bookmakers to Rank Esports Teams"
    dateFmt = "2006.01.02 15:04"
    titleCaseStyle = "none"

# Header
[menu]
  [[menu.main]]
        identifier = "rankings"
        name = "Bookmaker Rankings"
        url = "/rankings/"
        weight = 1
  
  [[menu.main]]
        identifier = "personal_rankings"
        name = "My Rankings"
        url = "/my_rankings/"
        weight = 2

# Footer
    [[menu.footer]]
        name = "Twitter"
        url = "https://x.com/dougliebe"
        weight = 2 

